# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8909bc3c5acca72723a5744d31dd6a6f18a0e2af75a05eada2a2b2fd3a1fe09d0ec4078df23bee68835b5d633dfb2e4c563845293ba912d3195cfe00824c75f9

test:
  secret_key_base: c627893872dd038540b3e23152d7d99a55a6b458c1b268724de6a5de4edfa6fdbe5f6bb38894eb0368db132feaf83ce7079f5b4b6907ae7fa2284fc75977f58e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
